--require each map here
--require "map_gen.mps_0_16.main"
require "map_gen.shapes.main"
require "map_gen.mps_0_17.main"
--require "map_gen.scrapyard.main"
-- require "map_gen.dangOreus"
-- require "map_gen.heximaze"
-- require "map_gen.heximazing"
-- require "map_gen.rail_grid"
-- require "map_gen.searious"